#!/bin/bash
### BEGIN INIT INFO
# Provides:          dnsforward
# Required-Start:
# Required-Stop:
# X-Start-Before:
# X-Stop-After:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Start the dnsforwarder
# Description:       Start the dnsforwarder which forwards different zones to different servers
### END INIT INFO

dnsforward="/usr/local/bin/dnsforward"
DEFAULTS="/etc/default/dnsforward"

# Check for daemon presence
[ -x "$dnsforward" ] || exit 0

# Include dnsforward defaults if available
[ -r "$DEFAULTS" ] || exit 0

. "$DEFAULTS"

# Get lsb functions
. /lib/lsb/init-functions

case "$1" in
  start)
    log_begin_msg "Starting dnsforward..."
    start-stop-daemon --start --quiet --oknodo --exec "$dnsforward" -- -d "${OPTIONS[@]}"
    log_end_msg $?
    ;;
  stop)
    log_begin_msg "Stopping dnsforward..."
    start-stop-daemon --stop --quiet --oknodo --retry 2 --exec "$dnsforward"
    log_end_msg $?
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  status)
    status_of_proc "$dnsforward" dnsforward
    ;;
  *)
    log_success_msg "Usage: /etc/init.d/dnsforward {start|stop|restart|status}"
    exit 1
esac
