#!/bin/bash
### BEGIN INIT INFO
# Provides:          hexns
# Required-Start:
# Required-Stop:
# X-Start-Before:
# X-Stop-After:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Start the Hexspeak nameserver
# Description:       Start the Hexspeak nameserver which translates domain names to ipv6 addresses.
### END INIT INFO

HEXNS="/usr/local/bin/hexns"
DEFAULTS="/etc/default/hexns"

# Check for daemon presence
[ -x "$HEXNS" ] || exit 0

# Include hexns defaults if available
[ -r "$DEFAULTS" ] || exit 0

. "$DEFAULTS"

# Get lsb functions
. /lib/lsb/init-functions

case "$1" in
  start)
    log_begin_msg "Starting hexns..."
    start-stop-daemon --start --quiet --oknodo --exec "$HEXNS" -- -d "${OPTIONS[@]}"
    log_end_msg $?
    ;;
  stop)
    log_begin_msg "Stopping hexns..."
    start-stop-daemon --stop --quiet --oknodo --retry 2 --exec "$HEXNS"
    log_end_msg $?
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  status)
    status_of_proc "$HEXNS" hexns
    ;;
  *)
    log_success_msg "Usage: /etc/init.d/hexns {start|stop|restart|status}"
    exit 1
esac
